name: DiscordSRV
version: @version@
main: github.scarsz.discordsrv.bukkit.BukkitPlugin
authors: [Scarsz, Androkai]
description: The most powerful, configurable, open-source Discord bridge plugin out there.
website: https://github.com/Scarsz/DiscordSRV
